common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views # django.contrib.auth 앱 views 파일의 별명
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'), #이 링크의 별명은 'login'
    #django.contrib.auth 앱 views 파일의 LoginView 클래스의 as_view() 함수 사용
    path('logout/', views.logout_view, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'), # '/'에 해당되는 path
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

# path 끝에 comma(,) 잊지 말기
urlpatterns = [
    path('', views.index, name='index'), # config\urls.py에 이미 'pybo/'가 존재함 -> ''로만 써도 열림
    path('<int:question_id>/', views.detail, name='detail'), # '정수형:질문 ID/'로 된 URL을 views.py의 detail 함수에 매핑
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

common/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect

def logout_view(request):
    logout(request)
    return redirect('index')

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Answer
from django.http import HttpResponseNotAllowed
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    """
    pybo 목록 출력
    """
    # 입력 인자
    page = request.GET.get('page', '1')    # 1페이지 가져와서 페이지(page) 객체를 만듬
    # 조회
    question_list = Question.objects.order_by('-create_date')
    # 페이징 처리
    paginator = Paginator(question_list, 10)   # 전체 question_list를 10개씩 묶어서 각 페이지로 만들기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}     # question_list는 페이징 객체(page_obj)임
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":            #POST 방식이라면,
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:                                   # GET 방식이면(POST 방식이 아니라면)
        return HttpResponseNotAllowed('Only POST is possible.')   # ‘POST만 가능합니다' 오류 발생
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

def question_create(request):
    if request.method == 'POST': # 요청이 POST 방식이면
        form = QuestionForm(request.POST)
        if form.is_valid():  # 폼이 유효하다면
            question = form.save(commit=False)  # 임시 저장하여 question 객체를 리턴받는다.
            question.create_date = timezone.now()  # 실제 저장을 위해 작성일시를 설정한다.
            question.save()  # 데이터를 실제로 저장한다.
            return redirect('pybo:index') # pybo:index로 이동함, 실 주소는 localhost:8000/pybo/
    else:                       # 요청이 POST 방식이 아니면 (GET 방식이면)
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>      <!-- 오류 표시 있지만, 무시해도 됨 -->
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %} <!--에러 시 사용할 템플릿 가져옴, 아직 안 만듦-->
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}           <!--폼에 에러가 있다면-->
<div class="alert alert-danger">
    {% for field in form %}    <!--폼에서 필드를 하나씩 가져와서-->
    <!-- 필드 오류 -->
    {% if field.errors %}       <!--해당 필드가 에러라면/ 값이 없거나 형식이 불일치인 경우-->
    <div>
        <strong>{{ field.label }}</strong>  <!--필드 라벨 굵게 출력-->
        {{ field.errors }}                    <!--필드 에러 메시지 출력-->
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 --> <!--필드 에러가 아닌 경우 겠죠-->
    {% for error in form.non_field_errors %}  <!--폼에 넌필드 에러를 하나씩 가져와서 -->
    <div>
        <strong>{{ error }}</strong>     <!--넌필드 에러 메시지를 출력-->
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav"> <!--기존 코드 navbar-nav 뒤 me-auto mb-2 mb-lg- 삭제-->
                <li class="nav-item">
                    {% if user.is_authenticated %} <!--user가 인증되었다면, 로그인 되었다면-->
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %} <!--로그아웃 상태면-->
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>

    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}        <!--question_create 함수에서 form.is_valid()에 에러가 있다면-->
        <div class="alert alert-danger" role="alert"> <!--경고 형식(분홍색 바탕에 글씨, 결과화면으로 확인) -->
            {% for field in form %} <!--폼에서 필드를 하나씩 가져오기-->
            {% if field.errors %} <!--필드에 에러가 있으면-->
            <div>
                <strong>{{ field.label }}</strong> <!--굵은 글씨로 해당필드 라벨 표시-->
                {{ field.errors }} <!--장고 폼에서 정한 에러가 표시됨(한글로 번역되어 표시) -->
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %} <!-- sub 필터 로드-->
{% block content %}
<div class="container my-3">     <!-- class에 “부트스트랩에 정의된 class 스타일” 적용-->
    <table class="table">
        <thead>                  <!-- <thead>: table head(구조) -->
        <tr class="table-dark">     <!-- <tr>: table row 1개-->
            <th>번호</th>             <!-- <th>: table head-->
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>                   <!-- <tbody>: table body(구조) -->
        {% if question_list %}            <!-- question_list 가 있으면 -->
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                <!--링크 받아, 제목 출력-->
                {% if question.answer_set.count > 0 %} <!-- 답변 개수가 0보다 크면, 답변이 있다면-->
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %} <!-- 답변 개수 출력 -->
            </td>
            <td>{{ question.create_date }}</td>
        </tr>    <!--질문 작성일시 출력-->
        {% endfor %}
        {% else %}                     <!-- question_list가 없으면-->
        <tr>
            <td colspan="3">질문이 없습니다.</td>    <!--열 3개 병합하여 ‘질문없습니다’ 출력-->
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}   <!-- 이전 페이지가 있다면 -->
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>                <!-- 이전 페이지 번호로 링크를 만들어, [이전] 버튼의 링크 활성화 -->
        {% else %}   <!-- 이전 페이지가 없다면 -->
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>              <!-- 포거스 제거(-1), 현재상태 비활성화(true), 링크 비활성화 -->
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}  <!-- 페이지 리스트 루프 -->
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}     <!-- 현재 페이지와 같으면 -->
        <li class="page-item active" aria-current="page"> <!-- active 클래스 적용하여 강조표시 -->
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>                 <!-- 페이지 번호로 링크를 만들어, [페이지 번호]의 링크를 활성화 -->
        {% else %}      <!-- 현재 페이지와 다르면 -->
        <li class="page-item"> <!-- active 클래스 없음, 강조표시 없음-->
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>                   <!-- 강조가 없을 뿐, [페이지 번호]의 링크는 활성화 -->
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}  <!-- 다음 페이지가 있다면 -->
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}  <!-- 다음 페이지가 없다면 -->
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}